Desktop/project3/Buddy/config/routes.rb
Rails.application.routes.draw do
  root  'events#index'

  resources :events
  resources :event_users
  get 'my_events', to: 'events#my_events'

  devise_for :users

end

Desktop/project3/Buddy/app/models/event.rb
class Event < ActiveRecord::Base

paginates_per 7

geocoded_by :address
after_validation :geocode
  
has_many :users, :through => :event_users
has_many :event_users

validates :event_name, presence: true, length: {minumum: 2, maximum: 25}
validates :description, presence: true, length: {minumum: 2, maximum: 200}
validates :date, presence: true, length: {minumum: 2, maximum: 15}
validates :time, presence: true, length: {minumum: 2, maximum: 15}
validates :address, presence: true, length: {minumum: 10, maximum: 50}
validates :location, length: {minumum: 2, maximum: 100}
validates :difficulty, length: {minumum: 2, maximum: 20}

end

Desktop/project3/Buddy/app/models/event_user.rb
class EventUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

Desktop/project3/Buddy/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :rsvps, :through => :event_users, class_name: "Events"
has_many :event_users
has_many :events, :through => :event_users
end

Desktop/project3/Buddy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

Desktop/project3/Buddy/app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController

def create
    current_user.event_users.create(params.require(:event_user).permit(:event_id))
    redirect_to my_events_path
end


end

Desktop/project3/Buddy/app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  def index
    @event = EventUser.all
    @events = Event.order(created_at: :desc).page(params[:page]).per(7)
  end

  def my_events
    @events = current_user.events.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create(event_params)
    @user_events = current_user.events
      if @event.save
        flash[:notice] = "Your Event was created"
         redirect_to event_path(@event)
      else
        flash[:notice] = "Your Event did not get created, retry !"
         redirect_to new_event_path
       end
  end

  def edit
    @event = Event.find(params[:id])
      # if @event.user_id != current_user.id
    #    flash[:error]= "You don't have permission to do that"
    #      redirect_to events_path
    # end
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find_by_id(params[:id])
    @event.destroy
    redirect_to request.referer
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :description, :address, :time, :date, :difficulty,:location)
  end

end

Desktop/project3/Buddy/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/project3/Buddy/app/helpers/event_users_helper.rb
module EventUsersHelper
end

Desktop/project3/Buddy/app/helpers/events_helper.rb
module EventsHelper
end

Desktop/project3/Buddy/app/views/events/_event.html.erb
<p></p>
  Workout: <%=event.event_name %>
  Description: <%=event.description %><br>
  Date: <%=event.date %>
  Time: <%=event.time %>
  Address:<%=event.address %>
  Location:<%=event.location %><br>
  Difficulty:<%=event.difficulty %>

Desktop/project3/Buddy/app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

Desktop/project3/Buddy/app/views/events/edit.html.erb
<%= form_for(@event) do |f| %>

  <div class="field">
    <%= f.label :Workout %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
      <%= f.label :Date %>
    <%= f.text_field :date %>
        <%= f.label :Time %>
    <%= f.text_field :time %>
        <%= f.label :Address %>
    <%= f.text_field :address %><br>
        <%= f.label :Location %>
    <%= f.text_field :location %>
        <%= f.label :Difficulty %>
    <%= f.text_field :difficulty %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Desktop/project3/Buddy/app/views/events/index.html.erb
<%= paginate @events %>

<%= link_to("New Event", new_event_path) %>

<%= link_to("My Events", my_events_path) %>

<% if current_user %>
  <% @events.each do |event| %>
      <%= render partial: 'event', locals: {event:event} %>
        <br>
        <% if current_user && event.event_users.where(user_id:current_user.id).first %>

            <%=link_to("map", event_path(event))%>

            <h3>You have joined this group</h3>
            
        <% else %>

              <%= form_for event.event_users.new do |f| %>
              <%= f.hidden_field :event_id, value: event.id %>
              <%= f.submit "JOIN GROUP" %>
              <% end %>

        <% end %>
          
          <%= link_to("New Event", new_event_path) %>
          <%= link_to("My Events", my_events_path) %>
  <% end %>      
<% else %> 
      <h3>Please Sign in to Join an Event</h3>

      <% @events.each do |event| %>
      Workout: <%=event.event_name %>
      Description: <%=event.description %><br>
      Date: <%=event.date %>
      Time: <%=event.time %>
      Dificulty: <%=event.difficulty %>
      <% end %>
<% end %>

Desktop/project3/Buddy/app/views/events/my_events.html.erb
<h2><strong>My Events</strong></h2>

<tbody>
  <% @events.each do |event| %>
      
    <%= render partial: "event", locals:{event: event} %>
      
    <br><%= link_to 'Edit', edit_event_path(event) %>
    <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %><br>
        
  <% end %>
  <div><br><%= link_to 'All Workouts', events_path %></div>
  
</tbody>

Desktop/project3/Buddy/app/views/events/new.html.erb
<%= form_for (@event) do |f| %>
  <%= f.label :Event %>
  <%= f.text_field :event_name %><br>
  <%= f.label :Description %>
  <%= f.text_area :description %><br>
  <%= f.label :Address %>
  <%= f.text_field :address %><br>
  <%= f.label :time %>
  <%= f.text_field :time %><br>
  <%= f.label :Date %>
  <%= f.text_field :date %><br>
  <%= f.label :Difficulty %>
  <%= f.text_field :difficulty %><br>

<%= f.submit %>
<% end %>

Desktop/project3/Buddy/app/views/events/show.html.erb
<p>
  <strong>Name:</strong><%= @event.event_name %>
   <strong>Description:</strong> <%= @event.description %>
    <strong>Date:</strong><%= @event.date %>
    <strong>Time:</strong><%= @event.time %>
    <strong>Address:</strong><%= @event.address %><p></p><br>

    <%=image_tag("http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}")%>
</p>


<%= link_to 'Back', events_path %>
<br>
 
<%  current_user.events.each do |event| %>
<%= event.event_name  %>
<%= link_to "Edit", edit_event_path(event) %>
<%= link_to 'Delete', event, method: :delete, data:{confirm: "Are you Certain"} %>
<br>
<% end %>

<%= link_to 'Back', events_path %>

Desktop/project3/Buddy/app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

Desktop/project3/Buddy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>